AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wappalyzer-js-cli

  SAM Template for wappalyzer-js-cli
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:
  QueueName:
    Type: String
    Description: Name of the queue triggering function
  QueueArn:
    Type: String
    Description: ARN of the queue triggering function

Resources:
  WappalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Policies: 
        - SQSSendMessagePolicy:
            QueueName:
              Ref: QueueName
      MemorySize: 1024
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue:
              Ref: QueueArn
            BatchSize: 1
            Enabled: true
    Metadata:
      DockerTag: nodejs20.x-v1
      DockerContext: .
      Dockerfile: Dockerfile